// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class ContactWithRegion
{
    public int Id { get; set; }

    public int RegionTaxonomyId { get; set; }

    public int ContactId { get; set; }

    public virtual ResourceContact Contact { get; set; }

    public virtual RegionTaxonomy RegionTaxonomy { get; set; }
}