// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class Organization
{
    public int Id { get; set; }

    public string Name { get; set; }
   
    public string WebsiteUrl { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public virtual ICollection<OrganizationAddress> OrganizationAddresses { get; set; } = new List<OrganizationAddress>();

    public virtual ICollection<ResourceProgram> ResourcePrograms { get; set; } = new List<ResourceProgram>();

    public virtual ICollection<ResourceContact> ResourceContacts { get; set; } = new List<ResourceContact>();
}