// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class RegionTaxonomy
{
    public int Id { get; set; }

    public string Region { get; set; }

    public int TaxonomyLeft { get; set; }

    public int TaxonomyRight { get; set; }

    public virtual ICollection<ResourceWithRegion> RegionWithResources { get; set; } = new List<ResourceWithRegion>();

    public virtual ICollection<ContactWithRegion> RegionsWithContacts { get; set; } = new List<ContactWithRegion>();
}