// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class ResourceLanguage
{
    public int Id { get; set; }

    public string LanguageName { get; set; }

    public virtual ICollection<ResourceWithLanguage> LanguageWithResources { get; set; } = new List<ResourceWithLanguage>();

    public virtual ICollection<ContactWithLanguage> LanguageWithContacts { get; set; } = new List<ContactWithLanguage>();
}