// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class ResourceApplicationType
{
    public int Id { get; set; }

    public string ApplicationType { get; set; }

    public virtual ICollection<ResourceWithApplicationType> ApplicationTypesWithResources { get; set; } = new List<ResourceWithApplicationType>();
}