// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class ResourceProgramDetail
{
    public int Id { get; set; }

    public int ResourceId { get; set; }

    public int? ProcessTimeId { get; set; }

    public string Cost { get; set; }

    public byte? CustomerServiceRating { get; set; }

    public byte? ObtainabilityRating { get; set; }

    public virtual ResourceProcessTime ProcessTime { get; set; }

    public virtual ResourceProgram Resource { get; set; }
}