// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class ResourceProcessTime
{
    public int Id { get; set; }

    public string TimeCategory { get; set; }

    public virtual ICollection<ResourceProgramDetail> ResourceProgramDetails { get; set; } = new List<ResourceProgramDetail>();
}