// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Nodes;
using System.Text.Json.Serialization;

namespace MigrateTOUData.Data.Models;

public partial class ResourceProgramStatus
{
    public int Id { get; set; }

    public int ResourceId { get; set; }

    public int StatusTypeId { get; set; }

    public DateTime Timestamp { get; set; }

    public string Notes { get; set; }

    public string CmsUser { get; set; }

    [JsonIgnore]
    public virtual ResourceProgram Resource { get; set; }

    public virtual ResourceStatusType StatusType { get; set; }
}