// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MigrateTOUData.Data.Models;

public partial class ResourceActivity
{
    public int Id { get; set; }

    public int ResourceId { get; set; }

    public int ActivityTypeId { get; set; }

    public int ActivityDetailId { get; set; }

    public string CmsUser { get; set; }

    public DateTime Timestamp { get; set; }

    public virtual ResourceActivityDetail ActivityDetail { get; set; }

    public virtual ResourceActivityType ActivityType { get; set; }

    [JsonIgnore]
    public virtual ResourceProgram Resource { get; set; }
}