// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
namespace MigrateTOUData.Data.Models;

public partial class ResourceContact
{
    public int Id { get; set; }

    public int OrgId { get; set; }

    public string Title { get; set; }

    public string FirstName { get; set; }

    public string MiddleName { get; set; }

    public string LastName { get; set; }

    public string Suffix { get; set; }

    public string OrgTitle { get; set; }

    public string Phone { get; set; }

    public string PhoneExt { get; set; }

    public string Mobile { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public virtual Organization Org { get; set; }

    public virtual ICollection<ContactWithLanguage> ContactWithLanguages { get; set; } = new List<ContactWithLanguage>();

    public virtual ICollection<ContactWithRegion> ContactWithRegions { get; set; } = new List<ContactWithRegion>();

    public virtual ICollection<ResourceWithContact> ContactWithResources { get; set; } = new List<ResourceWithContact>();
}