// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;
namespace MigrateTOUData.Data.Models;

public partial class ResourceActivityType
{
    public int Id { get; set; }

    public string ActivityType { get; set; }

    [JsonIgnore]
    public virtual ICollection<ResourceActivity> ResourceActivities { get; set; } = new List<ResourceActivity>();
}