// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class ServiceTaxonomy
{
    public int TaxonomyId { get; set; }

    public string Service { get; set; }

    public int TaxonomyLeft { get; set; }

    public int TaxonomyRight { get; set; }

    public virtual ICollection<ResourceWithService> ServicesWithResources { get; set; } = new List<ResourceWithService>();
}