// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class SituationTaxonomy
{
    public int Id { get; set; }

    public string Situation { get; set; }

    public int TaxonomyLeft { get; set; }

    public int TaxonomyRight { get; set; }

    public virtual ICollection<ResourceWithSituation> SituationsWithResources { get; set; } = new List<ResourceWithSituation>();
}