// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class UserSecurity
{
    public int Id { get; set; }

    public int ResourceUserId { get; set; }

    public byte[] Password { get; set; }

    public DateTime? TimestampLastLogin { get; set; }

    public virtual User ResourceUser { get; set; }
}