// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class User
{
    public int Id { get; set; }

    public string ResourceUserId { get; set; }

    public int RoleId { get; set; }

    public string Username { get; set; }

    public DateTime? TimestampLastUpdate { get; set; }

    public DateTime? TimestampCreated { get; set; }

    public virtual UserRole Role { get; set; }

    public virtual UserDetail Detail { get; set; } 

    public virtual ICollection<UserWithResourceFavorite> UserWithResourceFavorites { get; set; } = new List<UserWithResourceFavorite>();

    public virtual ICollection<UserWithResourceRating> UserWithResourceRatings { get; set; } = new List<UserWithResourceRating>();

    public virtual UserSecurity UserSecurity { get; set; }
}