// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MigrateTOUData.Data.Models;

public partial class UserRole
{
    public int Id { get; set; }

    public string Role { get; set; }

    public virtual ICollection<User> Users { get; set; } = new List<User>();
}